import { BadgeCheck, Download } from "lucide-react";
import { CampusPageHeader } from "@/components/campus/CampusPageHeader";
import { resolveCampusTenant } from "@/lib/campus/tenant";
import { EXAM_PERMIT, EXAM_TIMETABLE } from "@/lib/campus/student-data";
import { getStudentRecord } from "@/lib/campus/student";

type Props = { params: Promise<{ tenant: string }> };

export default async function ExamCentrePage({ params }: Props) {
  const { tenant: slug } = await params;
  const tenant = await resolveCampusTenant(slug);
  const student = await getStudentRecord(slug);

  return (
    <div>
      <CampusPageHeader
        badge="Student portal"
        title="Examination Centre"
        description={`Exam timetable, seat allocations, and your exam permit for ${tenant.name}.`}
      />

      <div
        className={`mb-6 rounded-xl border p-5 ${
          EXAM_PERMIT.status === "issued"
            ? "border-emerald-200 bg-emerald-50"
            : "border-rose-200 bg-rose-50"
        }`}
      >
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-start gap-3">
            <BadgeCheck className="mt-0.5 h-6 w-6 text-emerald-600" />
            <div>
              <p className="font-semibold text-slate-900">
                Exam permit {EXAM_PERMIT.status === "issued" ? "issued" : "blocked"}
              </p>
              <p className="text-sm text-slate-600">{EXAM_PERMIT.reason}</p>
              <p className="mt-1 text-xs text-slate-500">
                Permit {EXAM_PERMIT.permitNumber} · {student.studentNumber}
              </p>
            </div>
          </div>
          <button
            type="button"
            className="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white"
          >
            <Download className="h-4 w-4" /> Download permit (demo)
          </button>
        </div>
      </div>

      <h2 className="mb-3 text-lg font-semibold text-slate-900">Exam timetable</h2>
      <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white">
        <table className="min-w-full text-sm">
          <thead className="border-b border-slate-200 bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-4 py-3">Module</th>
              <th className="px-4 py-3">Date</th>
              <th className="px-4 py-3">Time</th>
              <th className="px-4 py-3">Venue</th>
              <th className="px-4 py-3">Seat</th>
            </tr>
          </thead>
          <tbody>
            {EXAM_TIMETABLE.map((e) => (
              <tr key={e.module} className="border-b border-slate-100 last:border-0">
                <td className="px-4 py-3">
                  <p className="font-medium text-slate-900">{e.module}</p>
                  <p className="text-xs text-slate-500">{e.title}</p>
                </td>
                <td className="px-4 py-3 text-slate-700">{e.date}</td>
                <td className="px-4 py-3 text-slate-700">{e.time}</td>
                <td className="px-4 py-3 text-slate-700">{e.venue}</td>
                <td className="px-4 py-3">
                  <span className="rounded-full bg-slate-100 px-2.5 py-0.5 font-semibold text-slate-800">
                    {e.seat}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-4 text-xs text-slate-500">
        Bring your exam permit and digital student ID to every venue. Seat numbers are generated by
        the Smart Examination Centre.
      </p>
    </div>
  );
}
