/** 25-module research learning curriculum for Research Understanding */

export type UnderstandingTopic = {
  module: string;
  title: string;
  items: string[];
};

export const UNDERSTANDING_RESEARCH_TOPICS: UnderstandingTopic[] = [
  {
    module: "MODULE 1: INTRODUCTION TO RESEARCH",
    title: "Introduction to Research",
    items: [
      "What is Research?",
      "Purpose of Research",
      "Characteristics of Research",
      "Importance of Research",
      "Types of Research",
      "Basic Research",
      "Applied Research",
      "Quantitative Research",
      "Qualitative Research",
      "Mixed Methods Research",
      "Action Research",
      "Experimental Research",
      "Descriptive Research",
      "Exploratory Research",
      "Correlational Research",
    ],
  },
  {
    module: "MODULE 2: IDENTIFYING A RESEARCH PROBLEM",
    title: "Identifying a Research Problem",
    items: [
      "Understanding Research Problems",
      "Sources of Research Problems",
      "Selecting a Research Topic",
      "Narrowing a Research Topic",
      "Research Gap Identification",
      "Problem Statement Development",
    ],
  },
  {
    module: "MODULE 3: RESEARCH TITLE DEVELOPMENT",
    title: "Research Title Development",
    items: [
      "Characteristics of a Good Research Title",
      "Formulating Research Titles",
      "Common Mistakes in Research Titles",
    ],
  },
  {
    module: "MODULE 4: RESEARCH OBJECTIVES AND QUESTIONS",
    title: "Research Objectives and Questions",
    items: [
      "Research Aim",
      "General Objectives",
      "Specific Objectives",
      "Research Questions",
      "Research Hypotheses",
      "Null Hypothesis",
      "Alternative Hypothesis",
    ],
  },
  {
    module: "MODULE 5: LITERATURE REVIEW",
    title: "Literature Review",
    items: [
      "What is a Literature Review?",
      "Importance of Literature Review",
      "Searching Academic Sources",
      "Reading Academic Articles",
      "Evaluating Sources",
      "Synthesizing Literature",
      "Identifying Research Gaps",
      "Writing Literature Reviews",
    ],
  },
  {
    module: "MODULE 6: THEORETICAL FRAMEWORK",
    title: "Theoretical Framework",
    items: [
      "Understanding Theory",
      "Role of Theory in Research",
      "Selecting Appropriate Theories",
      "Applying Theory in Research",
    ],
  },
  {
    module: "MODULE 7: CONCEPTUAL FRAMEWORK",
    title: "Conceptual Framework",
    items: [
      "Conceptual Framework Development",
      "Independent Variables",
      "Dependent Variables",
      "Moderating Variables",
      "Mediating Variables",
      "Diagram Construction",
    ],
  },
  {
    module: "MODULE 8: RESEARCH PARADIGMS",
    title: "Research Paradigms",
    items: ["Positivism", "Interpretivism", "Pragmatism", "Constructivism", "Critical Theory"],
  },
  {
    module: "MODULE 9: RESEARCH METHODOLOGY",
    title: "Research Methodology",
    items: [
      "What is Research Methodology?",
      "Research Approaches",
      "Quantitative Approach",
      "Qualitative Approach",
      "Mixed Methods Approach",
      "Research Designs",
      "Cross-Sectional Design",
      "Case Study Design",
      "Experimental Design",
      "Cohort Design",
      "Descriptive Design",
      "Exploratory Design",
    ],
  },
  {
    module: "MODULE 10: POPULATION AND SAMPLING",
    title: "Population and Sampling",
    items: [
      "Target Population",
      "Accessible Population",
      "Sampling Concepts",
      "Sample Size Determination",
      "Probability Sampling",
      "Simple Random Sampling",
      "Stratified Sampling",
      "Cluster Sampling",
      "Systematic Sampling",
      "Non-Probability Sampling",
      "Purposive Sampling",
      "Convenience Sampling",
      "Snowball Sampling",
      "Quota Sampling",
    ],
  },
  {
    module: "MODULE 11: DATA COLLECTION METHODS",
    title: "Data Collection Methods",
    items: [
      "Questionnaires",
      "Interviews",
      "Focus Group Discussions",
      "Observation",
      "Document Review",
      "Surveys",
      "Experiments",
    ],
  },
  {
    module: "MODULE 12: RESEARCH INSTRUMENTS",
    title: "Research Instruments",
    items: [
      "Questionnaire Design",
      "Interview Guide Development",
      "Observation Checklists",
      "Measurement Scales",
      "Nominal Scale",
      "Ordinal Scale",
      "Interval Scale",
      "Ratio Scale",
    ],
  },
  {
    module: "MODULE 13: VALIDITY AND RELIABILITY",
    title: "Validity and Reliability",
    items: [
      "Validity",
      "Content Validity",
      "Construct Validity",
      "Face Validity",
      "Criterion Validity",
      "Reliability",
      "Test-Retest Reliability",
      "Internal Consistency",
      "Cronbach's Alpha",
    ],
  },
  {
    module: "MODULE 14: DATA MANAGEMENT",
    title: "Data Management",
    items: ["Data Coding", "Data Entry", "Data Cleaning", "Data Storage", "Data Security"],
  },
  {
    module: "MODULE 15: QUANTITATIVE DATA ANALYSIS",
    title: "Quantitative Data Analysis",
    items: [
      "Descriptive Statistics",
      "Frequencies",
      "Percentages",
      "Mean",
      "Median",
      "Mode",
      "Standard Deviation",
      "Inferential Statistics",
      "T-Test",
      "Chi-Square Test",
      "Correlation Analysis",
      "Regression Analysis",
      "ANOVA",
      "Logistic Regression",
      "Statistical Software",
      "SPSS",
      "JASP",
      "Jamovi",
      "R",
      "Stata",
    ],
  },
  {
    module: "MODULE 16: QUALITATIVE DATA ANALYSIS",
    title: "Qualitative Data Analysis",
    items: [
      "Thematic Analysis",
      "Content Analysis",
      "Narrative Analysis",
      "Grounded Theory Analysis",
      "Coding Qualitative Data",
      "Theme Development",
      "Use of NVivo",
      "Use of ATLAS.ti",
    ],
  },
  {
    module: "MODULE 17: RESEARCH ETHICS",
    title: "Research Ethics",
    items: [
      "Research Ethics Principles",
      "Informed Consent",
      "Confidentiality",
      "Anonymity",
      "Beneficence",
      "Non-Maleficence",
      "Voluntary Participation",
      "Ethical Approval",
      "Research Misconduct",
      "Fabrication",
      "Falsification",
      "Plagiarism",
    ],
  },
  {
    module: "MODULE 18: ACADEMIC WRITING",
    title: "Academic Writing",
    items: [
      "Academic Writing Skills",
      "Scientific Writing",
      "Research Proposal Writing",
      "Thesis Writing",
      "Dissertation Writing",
      "Journal Article Writing",
      "Conference Paper Writing",
    ],
  },
  {
    module: "MODULE 19: REFERENCING AND CITATION",
    title: "Referencing and Citation",
    items: [
      "Why Referencing Matters",
      "APA 7th Edition",
      "Harvard Referencing",
      "Vancouver Referencing",
      "MLA Referencing",
      "Chicago Referencing",
      "In-Text Citations",
      "Reference Lists",
      "Reference Management Software",
      "Zotero",
      "Mendeley",
      "EndNote",
    ],
  },
  {
    module: "MODULE 20: PLAGIARISM AND ACADEMIC INTEGRITY",
    title: "Plagiarism and Academic Integrity",
    items: [
      "Understanding Plagiarism",
      "Types of Plagiarism",
      "Self-Plagiarism",
      "Paraphrasing Techniques",
      "Similarity Reports",
      "Academic Integrity",
    ],
  },
  {
    module: "MODULE 21: RESEARCH PROPOSAL WRITING",
    title: "Research Proposal Writing",
    items: [
      "Proposal Structure",
      "Introduction Chapter",
      "Literature Review Chapter",
      "Methodology Chapter",
      "References",
      "Appendices",
    ],
  },
  {
    module: "MODULE 22: THESIS AND DISSERTATION WRITING",
    title: "Thesis and Dissertation Writing",
    items: [
      "Chapter 1: Introduction",
      "Chapter 2: Literature Review",
      "Chapter 3: Methodology",
      "Chapter 4: Results",
      "Chapter 5: Discussion, Conclusions and Recommendations",
    ],
  },
  {
    module: "MODULE 23: RESEARCH PUBLICATION",
    title: "Research Publication",
    items: [
      "Journal Selection",
      "Manuscript Preparation",
      "Peer Review Process",
      "Open Access Publishing",
      "Predatory Journals",
      "Publication Ethics",
    ],
  },
  {
    module: "MODULE 24: RESEARCH PROJECT MANAGEMENT",
    title: "Research Project Management",
    items: [
      "Research Planning",
      "Time Management",
      "Budgeting",
      "Risk Management",
      "Research Monitoring and Evaluation",
    ],
  },
  {
    module: "MODULE 25: ADVANCED RESEARCH SKILLS",
    title: "Advanced Research Skills",
    items: [
      "Systematic Reviews",
      "Scoping Reviews",
      "Meta-Analysis",
      "Bibliometric Analysis",
      "Evidence-Based Practice",
      "Artificial Intelligence in Research",
      "Research Grant Writing",
      "Research Commercialization",
    ],
  },
];

export function getUnderstandingTopicOptions(): Array<{ module: string; label: string }> {
  const options: Array<{ module: string; label: string }> = [];
  for (const m of UNDERSTANDING_RESEARCH_TOPICS) {
    for (const item of m.items) options.push({ module: m.module, label: item });
  }
  return options;
}

export function getUnderstandingTopicCount(): number {
  return getUnderstandingTopicOptions().length;
}
