import type { LucideIcon } from "lucide-react";
import {
  Award,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  CalendarDays,
  ClipboardList,
  CreditCard,
  FileCheck,
  FileText,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Home,
  Inbox,
  LayoutDashboard,
  PartyPopper,
  Percent,
  QrCode,
  ScanFace,
  Settings,
  ShieldCheck,
  TrendingUp,
  Users,
  Wallet,
} from "lucide-react";
import type { CampusModuleId, CampusRole } from "./types";

export type CampusNavItem = {
  id: CampusModuleId;
  label: string;
  href: (tenant: string) => string;
  icon: LucideIcon;
  roles: CampusRole[] | "all";
  badge?: string;
  section?: string;
};

export const CAMPUS_NAV: CampusNavItem[] = [
  {
    id: "overview",
    label: "Overview",
    href: (t) => `/campus/${t}`,
    icon: LayoutDashboard,
    roles: "all",
  },
  {
    id: "inst-admin",
    label: "Institution Admin",
    href: (t) => `/campus/${t}/admin`,
    icon: Building2,
    roles: ["vc", "admin"],
    section: "Department portals",
  },
  {
    id: "registrar-portal",
    label: "Registrar",
    href: (t) => `/campus/${t}/registrar`,
    icon: ClipboardList,
    roles: ["vc", "admin", "registrar"],
    section: "Department portals",
  },
  {
    id: "lecturer-portal",
    label: "Lecturer Portal",
    href: (t) => `/campus/${t}/lecturer`,
    icon: GraduationCap,
    roles: ["vc", "admin", "lecturer"],
    section: "Department portals",
  },
  {
    id: "exam-office",
    label: "Examination Office",
    href: (t) => `/campus/${t}/exam-office`,
    icon: FileCheck,
    roles: ["vc", "admin", "registrar", "exams"],
    section: "Department portals",
  },
  {
    id: "executive",
    label: "Executive Centre",
    href: (t) => `/campus/${t}/executive`,
    icon: BarChart3,
    roles: ["vc", "admin", "finance"],
    badge: "VC",
    section: "Modules",
  },
  {
    id: "success",
    label: "Student Success AI",
    href: (t) => `/campus/${t}/success`,
    icon: GraduationCap,
    roles: ["vc", "admin", "registrar", "lecturer"],
    badge: "AI",
  },
  {
    id: "advisor",
    label: "AI Academic Advisor",
    href: (t) => `/campus/${t}/advisor`,
    icon: Bot,
    roles: ["student", "lecturer", "registrar"],
    badge: "AI",
  },
  {
    id: "crm",
    label: "Institutional CRM",
    href: (t) => `/campus/${t}/crm`,
    icon: Users,
    roles: ["vc", "admin", "registrar"],
  },
  {
    id: "finance",
    label: "Finance ERP",
    href: (t) => `/campus/${t}/finance`,
    icon: Building2,
    roles: ["vc", "admin", "finance"],
  },
  {
    id: "wallet",
    label: "Student Wallet",
    href: (t) => `/campus/${t}/wallet`,
    icon: Wallet,
    roles: ["student", "finance", "admin"],
  },
  {
    id: "digital-id",
    label: "Digital Campus ID",
    href: (t) => `/campus/${t}/digital-id`,
    icon: QrCode,
    roles: ["student", "lecturer", "it"],
  },
  {
    id: "attendance",
    label: "AI Attendance",
    href: (t) => `/campus/${t}/attendance`,
    icon: ScanFace,
    roles: ["lecturer", "admin", "registrar"],
  },
  {
    id: "exams",
    label: "Examination Centre",
    href: (t) => `/campus/${t}/exams`,
    icon: FileCheck,
    roles: ["lecturer", "registrar", "admin"],
  },
  {
    id: "lms",
    label: "Learning (LMS)",
    href: (t) => `/campus/${t}/lms`,
    icon: BookOpen,
    roles: ["student", "lecturer"],
  },
  {
    id: "research",
    label: "Research Hub",
    href: (t) => `/campus/${t}/research`,
    icon: Award,
    roles: ["vc", "admin", "lecturer"],
  },
  {
    id: "accreditation",
    label: "Accreditation & QA",
    href: (t) => `/campus/${t}/accreditation`,
    icon: ShieldCheck,
    roles: ["vc", "admin", "registrar"],
  },
  {
    id: "alumni",
    label: "Alumni & Fundraising",
    href: (t) => `/campus/${t}/alumni`,
    icon: HeartHandshake,
    roles: ["vc", "admin"],
  },
  {
    id: "employers",
    label: "Employers & Graduates",
    href: (t) => `/campus/${t}/employers`,
    icon: Briefcase,
    roles: ["vc", "admin", "student"],
  },
  {
    id: "verify",
    label: "Transcript Verify",
    href: (t) => `/campus/${t}/verify`,
    icon: CreditCard,
    roles: "all",
  },
  {
    id: "chatbot",
    label: "Campus AI Chat",
    href: (t) => `/campus/${t}/chatbot`,
    icon: Bot,
    roles: "all",
  },
];

/** Student super-app navigation — grouped sections, daily-value features first */
export const STUDENT_NAV: CampusNavItem[] = [
  {
    id: "student-home",
    label: "Dashboard",
    href: (t) => `/campus/${t}/student`,
    icon: LayoutDashboard,
    roles: ["student"],
  },
  {
    id: "registration",
    label: "Registration",
    href: (t) => `/campus/${t}/student/registration`,
    icon: ClipboardList,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "my-modules",
    label: "My Modules",
    href: (t) => `/campus/${t}/student/modules`,
    icon: BookOpen,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "timetable",
    label: "Timetable",
    href: (t) => `/campus/${t}/student/timetable`,
    icon: CalendarDays,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "results",
    label: "Results",
    href: (t) => `/campus/${t}/student/results`,
    icon: GraduationCap,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "progress",
    label: "Academic Progress",
    href: (t) => `/campus/${t}/student/progress`,
    icon: TrendingUp,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "my-attendance",
    label: "Attendance",
    href: (t) => `/campus/${t}/student/attendance`,
    icon: Percent,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "assessments",
    label: "Assessments",
    href: (t) => `/campus/${t}/student/assessments`,
    icon: FileCheck,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "exam-centre",
    label: "Examination Centre",
    href: (t) => `/campus/${t}/student/exams`,
    icon: ShieldCheck,
    roles: ["student"],
    section: "Academics",
  },
  {
    id: "fees",
    label: "Fees & Wallet",
    href: (t) => `/campus/${t}/student/fees`,
    icon: Wallet,
    roles: ["student"],
    section: "Finance",
  },
  {
    id: "documents",
    label: "Documents",
    href: (t) => `/campus/${t}/student/documents`,
    icon: FileText,
    roles: ["student"],
    section: "Services",
  },
  {
    id: "library",
    label: "Library",
    href: (t) => `/campus/${t}/student/library`,
    icon: BookMarked,
    roles: ["student"],
    section: "Services",
  },
  {
    id: "hostel",
    label: "Hostel",
    href: (t) => `/campus/${t}/student/hostel`,
    icon: Home,
    roles: ["student"],
    section: "Services",
  },
  {
    id: "digital-id",
    label: "Student ID",
    href: (t) => `/campus/${t}/digital-id`,
    icon: QrCode,
    roles: ["student"],
    section: "Services",
  },
  {
    id: "requests",
    label: "Requests",
    href: (t) => `/campus/${t}/student/requests`,
    icon: Inbox,
    roles: ["student"],
    section: "Services",
  },
  {
    id: "messages",
    label: "Messages",
    href: (t) => `/campus/${t}/student/messages`,
    icon: Inbox,
    roles: ["student"],
    section: "Campus Life",
  },
  {
    id: "announcements",
    label: "Announcements",
    href: (t) => `/campus/${t}/student/announcements`,
    icon: Bell,
    roles: ["student"],
    section: "Campus Life",
  },
  {
    id: "career",
    label: "Career Portal",
    href: (t) => `/campus/${t}/student/career`,
    icon: Briefcase,
    roles: ["student"],
    section: "Campus Life",
  },
  {
    id: "events",
    label: "Events",
    href: (t) => `/campus/${t}/student/events`,
    icon: PartyPopper,
    roles: ["student"],
    section: "Campus Life",
  },
  {
    id: "wellness",
    label: "Wellness Centre",
    href: (t) => `/campus/${t}/student/wellness`,
    icon: HeartPulse,
    roles: ["student"],
    section: "Campus Life",
  },
  {
    id: "advisor",
    label: "AI Assistant",
    href: (t) => `/campus/${t}/advisor`,
    icon: Bot,
    roles: ["student"],
    badge: "AI",
    section: "Smart Tools",
  },
  {
    id: "lms",
    label: "Learning (LMS)",
    href: (t) => `/campus/${t}/lms`,
    icon: BookOpen,
    roles: ["student"],
    section: "Smart Tools",
  },
  {
    id: "settings",
    label: "Settings",
    href: (t) => `/campus/${t}/student/settings`,
    icon: Settings,
    roles: ["student"],
    section: "Smart Tools",
  },
];

export function campusNavForRole(role: CampusRole): CampusNavItem[] {
  if (role === "student") return STUDENT_NAV;
  return CAMPUS_NAV.filter(
    (item) => item.roles === "all" || item.roles.includes(role)
  );
}

export function campusPath(tenant: string, module?: CampusModuleId): string {
  if (!module || module === "overview") return `/campus/${tenant}`;
  return `/campus/${tenant}/${module}`;
}
