import type { IntegrationSource } from "./types";

/** All sources — API-enabled ones query live; others open official search pages */
export const INTEGRATION_SOURCES: IntegrationSource[] = [
  // AI providers
  {
    id: "openai",
    name: "ChatGPT (OpenAI)",
    category: "ai",
    description: "Primary writing & analysis model",
    apiEnabled: true,
    requiresKey: "OPENAI_API_KEY",
    website: "https://openai.com",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    category: "ai",
    description: "Google generative AI",
    apiEnabled: true,
    requiresKey: "GEMINI_API_KEY",
    website: "https://ai.google.dev",
  },
  {
    id: "grok",
    name: "Grok (xAI)",
    category: "ai",
    description: "xAI model for research Q&A",
    apiEnabled: true,
    requiresKey: "XAI_API_KEY",
    website: "https://x.ai",
  },
  {
    id: "gptzero",
    name: "GPTZero",
    category: "ai",
    description: "Dedicated AI content detector (AI Detection module)",
    apiEnabled: true,
    requiresKey: "GPTZERO_API_KEY",
    website: "https://gptzero.me/developers",
  },
  // Literature & citations
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    category: "literature",
    description: "Research papers, citations, related studies",
    apiEnabled: true,
    requiresKey: "SEMANTIC_SCHOLAR_API_KEY",
    website: "https://www.semanticscholar.org",
    searchUrl: (q) =>
      `https://www.semanticscholar.org/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: "openalex",
    name: "OpenAlex",
    category: "literature",
    description: "Researchers, institutions, publications (replaces Microsoft Academic)",
    apiEnabled: true,
    website: "https://openalex.org",
    searchUrl: (q) => `https://openalex.org/works?page=1&filter=title.search:${encodeURIComponent(q)}`,
  },
  {
    id: "crossref",
    name: "Crossref / DOI",
    category: "citation",
    description: "DOI lookup, citation verification, reference metadata",
    apiEnabled: true,
    website: "https://www.crossref.org",
  },
  {
    id: "core",
    name: "CORE",
    category: "literature",
    description: "Millions of open-access papers",
    apiEnabled: false,
    website: "https://core.ac.uk",
    searchUrl: (q) => `https://core.ac.uk/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: "pubmed",
    name: "PubMed",
    category: "literature",
    description: "Medical and health sciences research",
    apiEnabled: true,
    website: "https://pubmed.ncbi.nlm.nih.gov",
    searchUrl: (q) =>
      `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(q)}`,
  },
  {
    id: "arxiv",
    name: "arXiv",
    category: "literature",
    description: "IT, AI, mathematics, engineering preprints",
    apiEnabled: true,
    website: "https://arxiv.org",
    searchUrl: (q) => `https://arxiv.org/search/?query=${encodeURIComponent(q)}`,
  },
  {
    id: "google-scholar",
    name: "Google Scholar",
    category: "literature",
    description: "No public API — opens Scholar search (use OpenAlex & Semantic Scholar for API results)",
    apiEnabled: false,
    website: "https://scholar.google.com",
    searchUrl: (q) => `https://scholar.google.com/scholar?q=${encodeURIComponent(q)}`,
  },
  // Open books & education
  {
    id: "open-textbook-library",
    name: "Open Textbook Library",
    category: "books",
    description: "Free peer-reviewed open textbooks",
    apiEnabled: false,
    website: "https://open.umn.edu/opentextbooks",
    searchUrl: (q) =>
      `https://open.umn.edu/opentextbooks/search?query=${encodeURIComponent(q)}`,
  },
  {
    id: "bccampus",
    name: "BCcampus Open Education",
    category: "education",
    description: "Open textbooks and OER for higher education",
    apiEnabled: false,
    website: "https://open.bccampus.ca",
    searchUrl: (q) =>
      `https://open.bccampus.ca/browse/?search=${encodeURIComponent(q)}`,
  },
  {
    id: "gutenberg",
    name: "Project Gutenberg",
    category: "books",
    description: "Free ebooks — classics and public domain",
    apiEnabled: false,
    website: "https://www.gutenberg.org",
    searchUrl: (q) => `https://www.gutenberg.org/ebooks/search/?query=${encodeURIComponent(q)}`,
  },
  {
    id: "internet-archive",
    name: "Internet Archive",
    category: "books",
    description: "Books, papers, and media for research",
    apiEnabled: false,
    website: "https://archive.org",
    searchUrl: (q) => `https://archive.org/search?query=${encodeURIComponent(q)}`,
  },
  // Open data
  {
    id: "oecd",
    name: "OECD Data",
    category: "data",
    description: "Economic and social statistics from OECD countries",
    apiEnabled: false,
    website: "https://data.oecd.org",
    searchUrl: (q) => `https://data.oecd.org/searchresults/?q=${encodeURIComponent(q)}`,
  },
  {
    id: "worldbank",
    name: "World Bank Open Data",
    category: "data",
    description: "Global development indicators",
    apiEnabled: true,
    website: "https://data.worldbank.org",
    searchUrl: (q) =>
      `https://data.worldbank.org/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: "un-data",
    name: "United Nations Data",
    category: "data",
    description: "UN statistical databases",
    apiEnabled: false,
    website: "https://data.un.org",
    searchUrl: (q) => `https://data.un.org/Search.aspx?q=${encodeURIComponent(q)}`,
  },
  {
    id: "who",
    name: "WHO Data",
    category: "data",
    description: "Global health statistics",
    apiEnabled: false,
    website: "https://www.who.int/data",
    searchUrl: (q) => `https://www.who.int/data/gho/search-results?q=${encodeURIComponent(q)}`,
  },
  {
    id: "unicef",
    name: "UNICEF Data",
    category: "data",
    description: "Child-focused global indicators",
    apiEnabled: false,
    website: "https://data.unicef.org",
    searchUrl: (q) => `https://data.unicef.org/resources/dataset/?q=${encodeURIComponent(q)}`,
  },
  {
    id: "ilo",
    name: "ILO Statistics",
    category: "data",
    description: "Labour and employment statistics",
    apiEnabled: false,
    website: "https://ilostat.ilo.org",
    searchUrl: (q) => `https://ilostat.ilo.org/search/?q=${encodeURIComponent(q)}`,
  },
  // Namibia & institutions
  {
    id: "nsa",
    name: "Namibia Statistics Agency",
    category: "institution",
    description: "Official Namibia statistics",
    apiEnabled: false,
    website: "https://nsa.org.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:nsa.org.na ${q}`)}`,
  },
  {
    id: "bon",
    name: "Bank of Namibia",
    category: "institution",
    description: "Economic and financial statistics",
    apiEnabled: false,
    website: "https://www.bon.com.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:bon.com.na ${q}`)}`,
  },
  {
    id: "mohss",
    name: "Ministry of Health and Social Services",
    category: "institution",
    description: "Namibia health policy & reports",
    apiEnabled: false,
    website: "https://www.mhss.gov.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:mhss.gov.na ${q}`)}`,
  },
  {
    id: "nust",
    name: "NUST",
    category: "institution",
    description: "Namibia University of Science and Technology",
    apiEnabled: false,
    website: "https://www.nust.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:nust.na ${q}`)}`,
  },
  {
    id: "unam",
    name: "University of Namibia",
    category: "institution",
    description: "UNAM research and publications",
    apiEnabled: false,
    website: "https://www.unam.edu.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:unam.edu.na ${q}`)}`,
  },
  // Research software (guides & official sites)
  {
    id: "spss",
    name: "IBM SPSS",
    category: "tools",
    description: "Statistical analysis software",
    apiEnabled: false,
    website: "https://www.ibm.com/spss",
    searchUrl: (q) =>
      `https://www.google.com/search?q=${encodeURIComponent(`SPSS tutorial ${q}`)}`,
  },
  {
    id: "r-project",
    name: "R Project",
    category: "tools",
    description: "Open-source statistical computing",
    apiEnabled: false,
    website: "https://www.r-project.org",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`R statistics ${q}`)}`,
  },
  {
    id: "jasp",
    name: "JASP",
    category: "tools",
    description: "Free intuitive statistical software",
    apiEnabled: false,
    website: "https://jasp-stats.org",
    searchUrl: (q) => `https://jasp-stats.org/search/${encodeURIComponent(q)}`,
  },
  {
    id: "jamovi",
    name: "Jamovi",
    category: "tools",
    description: "Free SPSS-like statistical software",
    apiEnabled: false,
    website: "https://www.jamovi.org",
    searchUrl: (q) =>
      `https://www.google.com/search?q=${encodeURIComponent(`jamovi ${q}`)}`,
  },
  {
    id: "nvivo",
    name: "NVivo",
    category: "tools",
    description: "Qualitative data analysis",
    apiEnabled: false,
    website: "https://lumivero.com/products/nvivo",
    searchUrl: (q) =>
      `https://www.google.com/search?q=${encodeURIComponent(`NVivo qualitative ${q}`)}`,
  },
  {
    id: "atlas-ti",
    name: "ATLAS.ti",
    category: "tools",
    description: "Qualitative analysis and coding",
    apiEnabled: false,
    website: "https://atlasti.com",
    searchUrl: (q) =>
      `https://www.google.com/search?q=${encodeURIComponent(`ATLAS.ti ${q}`)}`,
  },
  {
    id: "zotero",
    name: "Zotero",
    category: "tools",
    description: "Free reference manager",
    apiEnabled: false,
    website: "https://www.zotero.org",
    searchUrl: (q) => `https://www.zotero.org/support/?q=${encodeURIComponent(q)}`,
  },
  {
    id: "mendeley",
    name: "Mendeley",
    category: "tools",
    description: "Reference manager and research network",
    apiEnabled: false,
    website: "https://www.mendeley.com",
    searchUrl: (q) =>
      `https://www.google.com/search?q=${encodeURIComponent(`Mendeley ${q}`)}`,
  },
];

/** Sources used for broad academic search across the platform */
export const ACADEMIC_SEARCH_SOURCE_IDS = [
  "openalex",
  "semantic-scholar",
  "pubmed",
  "arxiv",
  "core",
] as const;

export function getSource(id: string) {
  return INTEGRATION_SOURCES.find((s) => s.id === id);
}
