import type { IntegrationSource } from "./types";

/** All sources — API-enabled ones query live; others open official search pages */
export const INTEGRATION_SOURCES: IntegrationSource[] = [
  // AI providers
  {
    id: "openai",
    name: "ChatGPT (OpenAI)",
    category: "ai",
    description: "Primary writing & analysis model",
    apiEnabled: true,
    requiresKey: "OPENAI_API_KEY",
    website: "https://openai.com",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    category: "ai",
    description: "Google generative AI",
    apiEnabled: true,
    requiresKey: "GEMINI_API_KEY",
    website: "https://ai.google.dev",
  },
  {
    id: "grok",
    name: "Grok (xAI)",
    category: "ai",
    description: "xAI model for research Q&A",
    apiEnabled: true,
    requiresKey: "XAI_API_KEY",
    website: "https://x.ai",
  },
  // Literature & citations
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    category: "literature",
    description: "Research papers, citations, related studies",
    apiEnabled: true,
    requiresKey: "SEMANTIC_SCHOLAR_API_KEY",
    website: "https://www.semanticscholar.org",
    searchUrl: (q) =>
      `https://www.semanticscholar.org/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: "openalex",
    name: "OpenAlex",
    category: "literature",
    description: "Researchers, institutions, publications (replaces Microsoft Academic)",
    apiEnabled: true,
    website: "https://openalex.org",
    searchUrl: (q) => `https://openalex.org/works?page=1&filter=title.search:${encodeURIComponent(q)}`,
  },
  {
    id: "crossref",
    name: "Crossref / DOI",
    category: "citation",
    description: "DOI lookup, citation verification, reference metadata",
    apiEnabled: true,
    website: "https://www.crossref.org",
  },
  {
    id: "core",
    name: "CORE",
    category: "literature",
    description: "Millions of open-access papers",
    apiEnabled: false,
    website: "https://core.ac.uk",
    searchUrl: (q) => `https://core.ac.uk/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: "pubmed",
    name: "PubMed",
    category: "literature",
    description: "Medical and health sciences research",
    apiEnabled: true,
    website: "https://pubmed.ncbi.nlm.nih.gov",
    searchUrl: (q) =>
      `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(q)}`,
  },
  {
    id: "arxiv",
    name: "arXiv",
    category: "literature",
    description: "IT, AI, mathematics, engineering preprints",
    apiEnabled: true,
    website: "https://arxiv.org",
    searchUrl: (q) => `https://arxiv.org/search/?query=${encodeURIComponent(q)}`,
  },
  {
    id: "google-scholar",
    name: "Google Scholar",
    category: "literature",
    description: "No public API — opens Scholar search (use OpenAlex & Semantic Scholar for API results)",
    apiEnabled: false,
    website: "https://scholar.google.com",
    searchUrl: (q) => `https://scholar.google.com/scholar?q=${encodeURIComponent(q)}`,
  },
  // Open data
  {
    id: "worldbank",
    name: "World Bank Open Data",
    category: "data",
    description: "Global development indicators",
    apiEnabled: true,
    website: "https://data.worldbank.org",
    searchUrl: (q) =>
      `https://data.worldbank.org/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: "un-data",
    name: "United Nations Data",
    category: "data",
    description: "UN statistical databases",
    apiEnabled: false,
    website: "https://data.un.org",
    searchUrl: (q) => `https://data.un.org/Search.aspx?q=${encodeURIComponent(q)}`,
  },
  {
    id: "who",
    name: "WHO Data",
    category: "data",
    description: "Global health statistics",
    apiEnabled: false,
    website: "https://www.who.int/data",
    searchUrl: (q) => `https://www.who.int/data/gho/search-results?q=${encodeURIComponent(q)}`,
  },
  {
    id: "unicef",
    name: "UNICEF Data",
    category: "data",
    description: "Child-focused global indicators",
    apiEnabled: false,
    website: "https://data.unicef.org",
    searchUrl: (q) => `https://data.unicef.org/resources/dataset/?q=${encodeURIComponent(q)}`,
  },
  {
    id: "ilo",
    name: "ILO Statistics",
    category: "data",
    description: "Labour and employment statistics",
    apiEnabled: false,
    website: "https://ilostat.ilo.org",
    searchUrl: (q) => `https://ilostat.ilo.org/search/?q=${encodeURIComponent(q)}`,
  },
  // Namibia & institutions
  {
    id: "nsa",
    name: "Namibia Statistics Agency",
    category: "institution",
    description: "Official Namibia statistics",
    apiEnabled: false,
    website: "https://nsa.org.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:nsa.org.na ${q}`)}`,
  },
  {
    id: "bon",
    name: "Bank of Namibia",
    category: "institution",
    description: "Economic and financial statistics",
    apiEnabled: false,
    website: "https://www.bon.com.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:bon.com.na ${q}`)}`,
  },
  {
    id: "mohss",
    name: "Ministry of Health and Social Services",
    category: "institution",
    description: "Namibia health policy & reports",
    apiEnabled: false,
    website: "https://www.mhss.gov.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:mhss.gov.na ${q}`)}`,
  },
  {
    id: "nust",
    name: "NUST",
    category: "institution",
    description: "Namibia University of Science and Technology",
    apiEnabled: false,
    website: "https://www.nust.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:nust.na ${q}`)}`,
  },
  {
    id: "unam",
    name: "University of Namibia",
    category: "institution",
    description: "UNAM research and publications",
    apiEnabled: false,
    website: "https://www.unam.edu.na",
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(`site:unam.edu.na ${q}`)}`,
  },
];

export function getSource(id: string) {
  return INTEGRATION_SOURCES.find((s) => s.id === id);
}
